parameters:
    statics.debug:                   %kernel.debug%
    pv_statics.manager.class:        Pv\StaticsBundle\StaticsManager
    pv_statics.cache.class:          Pv\StaticsBundle\Cache\FilesystemCache
    pv_statics.twig_extension.class: Pv\StaticsBundle\Twig\StaticsExtension
    statics.closure_compiler.jar:    %kernel.root_dir%/../bin/closure-compiler-20130411.jar
    statics.soy.jar:                 %kernel.root_dir%/../bin/soy-20121221.jar

services:
    statics.manager:
        class: %pv_statics.manager.class%
        arguments:
            - @service_container
            - @statics.cache
            - %kernel.root_dir%

    statics.cache:
        class: %pv_statics.cache.class%
        arguments:
            - %kernel.cache_dir%/statics

    statics.helper:
        class: Pv\StaticsBundle\StaticsHelper
        arguments:
            - @service_container
            - %statics.debug%

    statics.twig_extension:
        class: %pv_statics.twig_extension.class%
        arguments:
            - @service_container
            - %statics.debug%
        public: false
        tags:
            - { name: twig.extension }

    statics.loader:
        class: Pv\StaticsBundle\Loader\Loader
        arguments:
            - @kernel

    statics.url_helper:
        class: Pv\StaticsBundle\UrlHelper
        arguments:
            - @service_container

    statics.filters.css_include:
        class: Pv\StaticsBundle\Filter\CssIncludeFilter
        arguments:
            - @statics.manager

    statics.filters.js_include:
        class: Pv\StaticsBundle\Filter\JsIncludeFilter
        arguments:
            - @statics.manager

    statics.filters.lessphp:
        class: Pv\StaticsBundle\Filter\LessphpFilter
        arguments:
            - @statics.manager

    statics.filters.less:
        class: Pv\StaticsBundle\Filter\LessFilter

    statics.filters.closure_compiler:
        class: Pv\StaticsBundle\Filter\ClosureCompilerFilter
        arguments:
            - %statics.closure_compiler.jar%

    statics.filters.soy:
        class: Pv\StaticsBundle\Filter\SoyFilter
        arguments:
            - %statics.soy.jar%
